name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.5
  go_router: ^6.5.7
  riverpod_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.3.4
  riverpod_lint: ^1.3.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/